### ISSUE TITLE
First-Class Environment Support

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#107]
### Discussed in https://github.com/imageworks/spk/discussions/78#discussioncomment-824018

<div type='discussions-op-text'>

<sup>Originally posted by **rydrman** June 3, 2021</sup>
Thanks for writing this up, I think this is close to my idea, but for symmetry with the rest of the spec I would tweak it a little to:

```yaml
pkg: stdfs/1.0.0
install:
  environment:
    - set: PATH
      value: /spfs/lib
    - set: SDFS_ENABLED
      value: true
    - prepend: LIBRARY_PATH
      value: /spfs/lib
    - prepend: LD_LIBRARY_PATH
      value: /spfs/lib
```
Alternative separators could be used pretty easily (though you'd be relying on other packages to set the same override confounded)
```yaml
   - prepend: MYPATHVAR
     value: /spfs/path
     separator: ";"
```
</div>
