### ISSUE TITLE
`install.environment` config is lost when recipe is published

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#1081]
Given a recipe with `install.environment` rules:

```yaml
pkg: env/1.0.0

api: v0/package

build:
  script:
    - true

install:
  environment:
    - set: TEST
      value: test
```

After building this package, the recipe that is created has lost these rules:

```sh
$ spk info env/1.0.0
api: v0/package
pkg: env/1.0.0
sources:
- path: .
  exclude:
  - .git/
  - .svn/
  filter:
  - :- .gitignore
build:
  script:
  - 'true'
```

(`$ spfs read spk/spec/env/1.0.0` gives the same output.)

The rules can still be found in the `src` recipe (`$ spk info env/1.0.0/src`) but it would be better if they survived into the other recipes for visibility.
