### ISSUE TITLE
Improve License Validation Semantics

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#1170]
still put this in the metadata, but you _should_ be able to disable the license check - maybe this needs to be split out first to make this possible.

Aka split SpdxLicense rule into two (has license vs is spdx) and then make the semantics such that both can be disabled in these cases so that the actual included license is never checked.

```
build:
  validation:
    - rules: 
        - allow: SpdxLicense
        - allow: HasLicense
```
