### ISSUE TITLE
Package Metadata

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#152]
@alexxbb we talked about the structure already in the first comment. In terms of validation, I think that that is a repository-based thing. Eg you can have a package with no metadata but maybe publishing that package to some public server would fail (eg the server/repo requires metadata, not the underlying tool)

This is my understanding of the current proposed structure, I am happy to put my vote on this one for moving forward or at least use it to get to something more finalized:

```yaml
pkg: mypkg/1.0.0
meta:
  # short (50-80) characters about the package 
  headline: "" 
  # long form information about the package 
  # ** This one could also be "description" but I wanted to find something
  #    that was unambiguously a "long-form" field to contrast the headline.
  readme: ""
  # the main landing page for this software (github, custom site etc)
  homepage: ""
  # SPDX short designator for the license type (or as a default: UNLICENSED)
  license: ""
  # allows for user-defined k/v but intentionally implies short values
  # for the purpose of identification and categorization
  labels:
    department: rigging
```

**I think this set is a great place to start, and gives us a good base on which to build as we find other fields that we want to consider**

I'm also happy to totally remove `readme` and only allow the short headline - keeping package specs small since the system needs to load them a lot.

Thoughts on things not included:
  
- I think that the author can be more of a label rather than a builtin - I find that static author lists get out of date too easily and it's much better to have tooling which can simply inject relevant metadata (I'm thinking CI processes) and even to use more team-based labels that are studio/context specific.
- The last person who updated something also feels like it's better to get right from spfs as we talked about briefly in the last meeting. For the purposes of the ls command, for example, I think that this is much more valuable/likely to be what you want rather than the email of somebody who left the company years ago and just so happens to still be some static author list.
- Lastly, the date as well feels like something you can pull directly from spfs and is more likely to be up-to-date and valuable. This is likely tracked better in a future server-based remote repository as well which would further improve the ls command

_Originally posted by @rydrman in https://github.com/imageworks/spk/discussions/110#discussioncomment-1092926_
