### ISSUE TITLE
Add Script Source Package Requirements

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#179]
Based on the discussion today, this is going to be accepted as per the initial syntax:

```yaml
pkg: opencolorio/2.0.0
sources:
  # Clone the git repository.
  - git: https://github.com/AcademySoftwareFoundation/OpenColorIO
    ref: v2.0.0
  # Apply patches.
  - script:
      # "oss_tool" is an executable provided by the "oss_tool" package.
      # and this is assuming we're in the root dir of the cloned repo - or do we have to cd to "src" first?
      - oss_tool apply 
    requirements:
      - pkg: oss_tool
 ```

_Originally posted by @rydrman in https://github.com/imageworks/spk/discussions/81#discussioncomment-1405529_
