### ISSUE TITLE
Implement Package Components

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#192]
A package **component** is defined to represent a subset of the files. Components are:
- named
- able to supplement and override the default requirements
- can be composed by _using_ each other
- must all share the same version in a resolved environment
- referenced downstream with the `package.component` syntax
- the system will recognize a default set of `.build`, `.run`, and `.all` components
  - these would be used by spk in different contexts (build envs vs cli vs runtime requirements)

```yaml

install:
  requirements:
    - pkg: stdfs
    - pkg: python.bin
  components:
    - name: devel
      files: 
         - include/**
         - lib/pkgconfig/
    - name: lib
      files: "lib/**"
      requirements:
        - pkg: gcc
          fromBuildEnv: Binary
          include: IfAlreadyPresent
    - name: bin
      files: "bin/**"
      use: [lib]
```

file patterns:
 - use the same format and semantics of gitignore rules

```sh
spk env python.bin/3.7
```

implications:
 - we should add a validator for files that are not captured (which can be disabled)
 - let's circle back on other conventions or tooling around debug packages, other component names etc

_Originally posted by @rydrman in https://github.com/imageworks/spk/discussions/80#discussioncomment-1473597_
