### ISSUE TITLE
Allow lists in variants for auto-generation of option matrix

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#226]
I think that this idea is best shown with a simple example

```yaml
build:
  options:
    - pkg: gcc
    - pkg: python
  variants:
   - { gcc: [4.8, 6.3], python: [2.7, 3.7] }
  # the above single line would be the same as the following 4
  - { gcc: 4.8, python: 2.7 }
  - { gcc: 4.8, python: 3.7 }
  - { gcc: 6.3, python: 2.7 }
  - { gcc: 6.3, python: 3.7 }
```

The general idea is to allow specifying lists inside of variants, and the system will expand out the list. You can then use multiple lists inside of a variant to get a product matrix for the different combinations.

Because we already de-duplicate variants, there are lots of opportunities to mix lists with single values or other lists and create more concise and easier to maintain spec files without much risk to any existing process.
