### ISSUE TITLE
API Versions in Specs

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#254]
Although we could assume that spec files that only have options are platforms, I think it would allow us to present a better user experience and better error messages to instead introduce an `api` field at the top level. This field allows us to distinguish different versions of the yaml format as well as different flavours.

```yaml
# the default value, to support old packages is assumed to be v0/package
pkg: my-package/1.0.0
api: v0/package
build:
  ...
```

```yaml
# packages leveraging the new-style spec will be v1, though we may
# choose to make this v1alpha until the changes settle
pkg: my-package/1.0.0
api: v1alpha/package
options:
    ...
```

```yaml
# this v1 api version will also define a platform spec
pkg: vfx/2020
api: v1alpha/platform
options:
  ...
```

_Originally posted by @rydrman in https://github.com/imageworks/spk/discussions/126#discussioncomment-2121987_
