### ISSUE TITLE
Namespaced package variables and their environment variable names

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#281]
When we have namespaced package variables, during the build an environment variable is generated with the namespaced name, including a period character. It turns out that this is inaccessible without jumping through hoops in bash.

```yaml
pkg: "parent/1.0.0"

build:
    options:
        - var: build_type/Release
          choices: ["Release", "Debug"]
    script:
        - env | grep SPK_OPT_parent.build_type
        - echo $SPK_OPT_parent.build_type
        - echo ${SPK_OPT_parent.build_type}
    variants:
        - {"parent.build_type": "Debug"}
        - {"parent.build_type": "Release"}
```

```shell
[info     ] building variant               variant={arch: x86_64, centos: 7, distro: centos, os: linux, parent.build_type: Debug}
+ env
+ grep SPK_OPT_parent.build_type
SPK_OPT_parent.build_type=Debug
+ echo .build_type
.build_type
/spfs/spk/pkg/parent/1.0.0/PYABKJZ2/build.sh: line 3: ${SPK_OPT_parent.build_type}: bad substitution
Build script returned non-zero exit status: 1
```

We need to transform the option names some other way to avoid using a `.`.
