### ISSUE TITLE
Pins should include post release info

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#451]
https://github.com/imageworks/spk/blob/53c4c421201e0acbf5b77a6144b344bb6d00ebdb/src/api/request.rs#L892

We established in a relatively recent change that a request for `2.1.3` also sets the floor version, so that `2.1.0` would not be allowed to satisfy a request for `2.1.3`. By extension, a request for `2.1.3+r.2` would (should) not be able to be satisfied by version `2.1.3`.

Therefore, for a spec like:

```yaml
build:
  options:
    - pkg: foo/2.1.3+r.2
install:
  requirements:
    - pkg: foo
      fromBuildEnv: Binary
```

We would expect this to be rendered as:

```yaml
build:
  options:
    - pkg: foo/2.1.3+r.2
install:
  requirements:
    - pkg: foo/2.1.3+r.2
```

This properly sets the floor version to the one used in the build environment. Currently, it is rendered as:

```yaml
build:
  options:
    - pkg: foo/2.1.3+r.2
install:
  requirements:
    - pkg: foo/2.1.3
```

This allows an earlier version of what was built against to be used.
