### ISSUE TITLE
Obstacles from using packages to simulate platform support

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#466]
We have created a series of different platform packages to coordinate build dependencies across a group of packages.

A platform package would take this shape:
```yaml
pkg: spi-platform/2022.4.0.0
compat: x.x.a.b
install:
  requirements:
    - pkg: openimageio/1.2.3
    - pkg: some-other-pkg/2.3.4
```
Notice that there are no build-time requirements and only install-time requirements.

There is also an empty package published with version 1.0:
```yaml
pkg: spi-platform/1.0
compat: x.x.a.b
```
This has no dependencies at all.

A package that uses the platform would have this shape:
```yaml
pkg: user/1.0
build:
  options:
    - pkg: spi-platform/=1.0
    - pkg: dcc-platform/=1.0
    - pkg: openimageio
  variants:
    - { spk-platform: 2022.4.0.0 }
    - { dcc-platform: 2022.4.0.0 }
install:
  requirements:
    - pkg: openimageio
      fromBuildEnv: Binary
```
This package is targeting two platforms. It has to declare each platform it is targeting as a build dependency. It sets them all to 1.0 by default, to pick up no dependencies. Each variant sets one of the platforms to a "real" platform version that does have dependencies.
It declares openimageio as a build time dependency, but with no version. This version will come from the platform dependency.

A build spec for `user` looks like this:
```yaml
pkg: user/1.0/ABC
build:
  options:
    - pkg: spi-platform/=1.0                                                                                                                                                                                                                                                              
      static: ~2022.4.1.4 
    - pkg: dcc-platform/=1.0
      static: ~1.0.0
    - pkg: openimageio
      static: ~1.2.3
install:
  requirements:
    - pkg: "openimageio/Binary:1.2.3"
    # nothing mentions platforms here
```
Each build for each platform variant will have that platform's version number embedded in it. The openimagio package is part of the platform, but also uses the platform to find its own dependencies, so it has a build spec that looks like `user`'s here.

We recently bumped our platform to `2022.7.0.0`. Nothing about openimageio or its dependencies changed, so a build of openimageio for `2022.4.0.0` should be just as good as a build for `2022.7.0.0`. However, we start to see weirdness for a package that's trying to build against the new platform, when no new builds of openimagio (for example) for the new platform have been built:

```yaml
pkg: user/1.0
build:
  options:
    - pkg: spi-platform/=1.0
    - pkg: dcc-platform/=1.0
    - pkg: openimageio
  variants:
    - { spi-platform: 2022.7.0.0 }
    - { dcc-platform: 2022.7.0.0 }
install:
  requirements:
    - pkg: openimageio
      fromBuildEnv: Binary
```

`spk env -o 'spi-platform=2022.7.0.0' user.spk.yml@build` will fail to resolve here because it can't satisfy openimageio's pinned build requirement for `spi-platform=2022.4.0.0`. Even though both versions of the platform ask for the same version of openimageio, and a build of that version exists. There just is no build of openimagio of that version that exists with the platform version pinned to `2022.7.0.0`.

What openimageio needs is a way to ask for the build-time dependencies from a platform without having that platform end up appearing as a build-time dependency in its built package.

While `spk env -o 'spi-platform=2022.7.0.0' user.spk.yml@build` fails, `spk build user.spk.yaml` can actually succeed. When solving for the `spi-platform` variant, it will reject the `spi-platform` build of openimageio, but can find some other build. I've seen it resolve an openimageio build from a _different_ platform, but can't explain why that's allowed to solve.
