### ISSUE TITLE
Epoch concept from rpm

### ISSUE THREAD

**Issue by DiegoTavares** [spkenv/spk#48]
We need a mechanism to release a breaking change to a package in a way that doesn't break dependent packages.

Example scenario: A package currently bundles a C++ library and python bindings together in the same package. Say I wanted to split this into two packages. If I create a new package version (version bump or post-release bump), then any other package relying on the package containing python bindings will break.

RPMs have a concept of an epoch which appears as a colon-separated prefix on the version number, e.g., 2:2.0.6 for `epoch == 2`. The epoch acts a namespace for version numbers and a higher version number in a different epoch would not be seen as a potential upgrade to a lower version number in a lower epoch.

In this example, an update could be released with a new epoch number that removes the python bindings, but any existing packages would not automatically start resolving that new package because it has a higher epoch. Downstream packages would have to opt-in to consuming this package from the new epoch.

(By @jrray)

**Comment by jrray** [comment]
I recall us discussing this and the conclusion was that we didn't need to add anything because var options provide a way to accomplish this.

We have a situation where a package (a C++ library) has a particular C++ namespace naming scheme in the code and there are a variety of other packages that have been built with this library and expect that specific naming scheme.

Now we want to introduce a second naming scheme and add a var option to the package that describes which naming scheme is in the build variant.

The problem comes from existing builds of packages that depend on this library were built before the var option was added, and so when solving for those packages it might pick a build of the library that has an incompatible namespace naming scheme.

So say `library/1.2.3` (compat x.a.b) exists with no var and `app` builds against it, using `fromBuildEnv: true`.
Then, two variants of `library/1.2.4` are published with a new var, one build with `- var: ns/old` and one with `- var: ns/new`.

If doing `spk env app` then when resolving `library` it could either:

1. pick `library/1.2.3` -- ✅ okay
2. pick `library/1.2.4` with `ns/old` -- ✅ better
3. pick `library/1.2.4` with `ns/new` -- ❌ not compatible!

Will using the "choices" attribute on a var force the 1 outcome? If so, that could make this work but not be able to allow the newer version(s) of the library to be picked up.

Vars have a concept of a default value. If `ns` is defined as:

```yaml
- var: ns/old
  choices: [old, new]
```

Will this steer `app` to the 2 outcome, or at least make it a valid choice? Or more importantly, will it successfully prevent the 3 outcome?

**Comment by jrray** [comment]
I just finished trying this out and did not get the desired behavior.

First building this:

```yaml
pkg: lib/1.0.0
api: v0/package
build:
  script:
    - true
```

Then this:

```yaml
pkg: app/1.0.0
api: v0/package
build:
  options:
    - pkg: lib
  script:
    - true
install:
  requirements:
    - pkg: lib
      fromBuildEnv: true
```

Then this:

```yaml
pkg: lib/1.0.1
api: v0/package
build:
  options:
    - var: ns/old
      choices:
        - old
        - new
  script:
    - true
  variants:
    - { ns: old }
    - { ns: new }
```

```
Completed builds:
   lib/1.0.1/src
   lib/1.0.1/25P63K35 variant index 0, {arch: x86_64, distro: arch, ns: old, os: linux}
   lib/1.0.1/4TUBBHXQ variant index 1, {arch: x86_64, distro: arch, ns: new, os: linux}
```

spk is willing to solve an environment with the "new" variant. The desired behavior is that this is a solve error.

```
$ spk explain app lib/1.0.1/4TUBBHXQ
Installed Packages:
  Package                        Version  Newest  Requested by
  local/app:run/=1.0.0/ZLRIQV4A  1.0.0    -       command line
  local/lib:run/=1.0.1/4TUBBHXQ  1.0.1    -       command line, app/1.0.0/ZLRIQV4A
```

It happens to pick the "old" variant if I don't try to ask for the new on, just out of a build id sort order coincidence.

**Comment by jrray** [comment]
I also tried without the default value set:

```yaml
    - var: ns
      choices:
        - old
        - new
```

... just in case that did anything differently but I got the same outcome.

I'm not entirely sure what putting the default there accomplishes, perhaps it could be made to produce this behavior we're looking for, or to be more cautious we could add a new attribute to vars to opt-in to this new kind of behavior.

**Comment by rydrman** [comment]
I definitely remember having a conversation about this in the past...

Ultimately, the issue to me is that although the `ns` option is attached to the new build, the solver won't care unless something provides an opinion/constraint. The [`inheritance`](https://spkenv.dev/ref/api/v0/package/#variableoption) on options forces this constraint into newly built packages, but it sounds like what we need to complete the feature is a new constraint that says a package cannot be resolved unless something has specifically asked for that option value, which doesn't exist yet.

Some kind of:

```yaml
pkg: lib/1.0.0
build:
  options:
    - var: ns
      choices: [old, new]
      inheritance: Strong
      required: true
```

> Note: to me this opens the question of whether this should be an install requirement rather than part of the build option, since it affects the usage at runtime not the build output. It's almost like a non-default component in that it has to be requested specifically by something (but for the whole package).

**Comment by rydrman** [comment]
from the meeting today:
  - although epochs work for this case, it more that the packages _wanted_ to have a variable from the start but didn't. Aka we want to resolve old packages as if they had the original value.
  ```yaml
  pkg: lib/1.0.0
  build:
    options:
      - var: ns
        choices: [old, new]
        inheritance: Strong
  
  install:
    requirements:
      - var: ns=new
        default: old
  ```

  - we store _almost_ the right amount of information to go back and patch. We can tell if a given package was in the build environment so the logic of determining if a spec should be updated is theoretically possible.

  ```json
  > cat /spfs/spk/pkg/python/3.10.14/XRXWBZOC/options.json 
  {
    "abi": "cp310m",
    "almalinux": "9.5",
    "arch": "x86_64",
    "distro": "almalinux",
    "gcc": ">=6.3",
    "gcc.almalinux": "9.5",
    "gcc.arch": "x86_64",
    "gcc.distro": "almalinux",
    "gcc.os": "linux",
    "gcc.stdfs": "~1.1",
    "os": "linux",
    "stdfs": "",
    "stdfs.os": "linux"
  }
  ```
