### ISSUE TITLE
Build Option Expansion (aka: spec templating)

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#508]
From the meet-up today It felt like we still haven't reached a conclusion for this particular proposal... was the "syntax-for-template-vs-shell-variable-substitution" the main thing we are still unsure about?

I would definitely lean towards not having to specify the `!opts` to engage variable substitution.  It adds visual noise to a otherwise clean spec!  It feels like we could use a unique-enough-syntax such that we dont need `!opts`.

As an example, using the jinja2 {{ }} syntax - it's still curly braces but the lack of $ prefix sets it apart:
```yaml
pkg: mypackage/{{version}}
sources:
  - tar: https://github.com/me/mypackage/archive/mypackage-v{{version}}.tar.gz
build:
  options:
    - var: version/1.0.0
  script:
    - cd mypackage-${SPK_OPT_version}
    - make install
```

_Originally posted by @rlei-weta in https://github.com/imageworks/spk/discussions/77#discussioncomment-820364_
