### ISSUE TITLE
spk with better yaml errors fails on valid package yaml that contains build options that use `choices:`

### ISSUE THREAD

**Issue by dcookspi** [spkenv/spk#519]
Running a spk build from the master branch just after the "better yaml errors" changes, I found `spk` would fail on valid package specs that contain build options that use `choices:` settings. This breaks spk for any published package that uses this setting.

For example, running this `spk explain python`,  produces this error:
```
ERROR Invalid package spec for python/3.9.7/EIEIOI: 
   | - {pkg: gcc, static: ~9.3.1}
   | - {pkg: stdfs, static: ~1.0}
   | - {pkg: bzip2, static: ~1.0.6}
 9 | - choices: [cp39d, cp39]
   |          ^ build.options[6]: option cannot specify  at line 9 column 12
   |   inheritance: Strong
   |   static: cp39
   |   var: abi/cp39
```
That python build is a valid package published a while ago. The related section of it's spec looks like this:
```
   ...
    - pkg: gcc
      static: ~9.3.1
    - pkg: stdfs
      static: ~1.0
    - pkg: bzip2
      static: ~1.0.6
    - var: abi/cp39
      choices:
        - cp39d
        - cp39
      inheritance: Strong
      static: cp39
    - var: debug/off
   ...
```
That should still be valid shouldn't it, @rydrman ?
