### ISSUE TITLE
Vars defined in embedded spec conflict with top level vars

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#551]
Given this example recipe:
```yaml
pkg: test/1.2.3

build:
  script:
    - "true"

install:
  embedded:
    - pkg: python/3.9
      build:
        options:
          - var: abi/cp39
```

The built package spec looks like this (abbreviated):
```yaml
pkg: test/1.2.3/ZYQUGGEI
build:
  options:
    - var: abi/cp39    <--- look here
      static: cp39
install:
  embedded:
    - api: v0/package
      pkg: python/3.9/embedded
      build:
        options:
          - var: abi/cp39
```

Notice how the embedded package's `abi` var was added to the containing package. Is this expected?

If a var with the same name is also defined in the containing package, like so:
```
pkg: test/1.2.3

build:
  options:
    - var: abi
  script:
    - "true"

install:
  embedded:
    - pkg: python/3.9
      build:
        options:
          - var: abi/cp39
```

Then when built, an invalid package is generated and fails to load:
```
$ spk info test
Invalid package spec for test/1.2.3/F22FY7PF: 
    |     filter:
    |       - ":- .gitignore"
    | build:
 12 |   script:
    |         ^ build: build option was specified more than once: abi at line 12 column 9
    |     - "true"
    |   options:
    |     - var: abi/cp39

try '--verbose' for more info
```
