### ISSUE TITLE
Set env vars explicitly in install specification

### ISSUE THREAD

**Issue by lgritz** [spkenv/spk#71]
Some packages need environment variables set, and currently this is accomplished by putting scripting commands in /spfs/etc/spfs/startup.d/activate-PKG.{csh,sh}. Very awkward, you have to do it separately for bash and csh, and it's not super clear from the package spec if you aren't looking for it.

I propose the following enhancement to the spec:

```
install:
    requirements:
      - pkg: stdfs
      - pkg: gcc
    env:
      - Foo_ROOT: blah
      - BAR_PATH: "${BAR_PATH}:${PREFIX}/lib/here/there"
```

Benefits:
* Clear as can be what's going on from reading the package spec.
* Don't need to do it separately for bash & csh -- spk can figure that out.
* More compact than the funny idiom `echo "export xxx=yyy" >> /spfs/etc/spfs/startup.d/activate-PKG.sh` (which must also be repeated, slightly differently, for csh).
* `spk ls` in some verbose mode can also list all the env vars that will be touched by a package -- very handy!
* Can still use the activate script in the rare cases where something more complex needs to happen than simply setting a few env variables.
