### ISSUE TITLE
How to make a package with components that embed components?

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#742]
I'm getting tripped up on trying to make a package that has components where those components are expected to embed specific components of some other package. In the case of boost and boost-python, here's a simplified concrete example of what I'm trying to do:

boost:build contains header.hpp
boost:run contains libwhatever.so.1.2.3, and the "build" component has `uses: [run]`.

The boost-python package is a full build of boost with python stuff enabled at build time, so it's split up into components in a way that mirrors the boost package. But the boost-python "build" component should embed the boost "build" component, likewise the "run" component should embed the boost "run" component.

What I've tried looks like this (boost-python.spk.yaml):
```yaml
install:
  components:
    - name: build
      files:
        - include/
        - lib/cmake/
        - lib/*.a
        - lib/*.so
      uses:
        - run
      embedded:
        - pkg: boost/1.76.0+r.3
          install:
            components:
              - name: build
                uses:
                  - run
    - name: run
      files:
        - "*"
      file_match_mode: Remaining
      embedded:
        - pkg: boost/1.76.0+r.3
          install:
            components:
              - name: run
```

I'm not sure about the `embedded` entries here and I don't believe this is accomplishing what I'm looking for. For example, I made this extra dummy package:
```yaml
pkg: dummy/1.0.0

sources: []

build:
  script: []

install:
  requirements:
    - pkg: boost:build/1.76.0+r.3
```

Note that it specifically depends on the "build" component of boost.

Then, I do this contrived thing: `spk env -vv dummy boost-python:run`. I ask for the dummy package and boost-python:run.

It solves and I get an environment like this:
```
Installed Packages:
  local/dummy:{build,run}/=1.0.0/3I42H3S6
  local/boost-python:run/=1.76.0+r.3/Q4VLNGUE
  boost/=1.76.0+r.3/embedded
```

What's wrong here is that boost:build is not satisfied. This environment doesn't actually have any of the boost[-python] build component's files in it. This environment needs to include `boost-python:build` to actually satisfy dummy's requirements. The presence of `boost/=1.76.0+r.3/embedded` appears to satisfy the solver but the environment is missing required files.
