### ISSUE TITLE
Features missing for `install.environment`

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#758]
We would like to retire an internally maintained (python) tool that we use to generate activation scripts for spk packages and start using the `install.environment` mechanism instead. There are a few things missing that have come up so far while attempting to port a package over to using this instead.

### Variable Substitutions

It is common to want to record some details about the built package into the activation script. Our tool is invoked during spk package build so it has full access to the environment when writing out the activation script. Here's an example what would ideally be possible:

```yaml
install:
  environment:
    - set: KTOA_VERSION
      value: $SPK_PKG_VERSION_BASE
    - set: KATANA_TAGLINE
      value: "With KtoA $${KTOA_VERSION}"
```

Example of the generated activation script (bash version):

```bash
export KTOA_VERSION="4.2.2.0"
export KATANA_TAGLINE="With KtoA ${KTOA_VERSION}"
```

The `KTOA_VERSION` var expects to have the `$SPK_PKG_VERSION_BASE` expanded at the time of the spk build, but the `KATANA_TAGLINE` var wants to embed the use of a variable into the activation script. I'm using `$$` as the way to "escape" here as a possible option.

### Activation Script Order

It is common for activation scripts to need to be run in a particular order between different packages, and the `install.environment` mechanism writes out activation scripts with names based on the package name, like: `spk_{package_name}.csh`. Some way is needed to override this name, like for example:

```yaml
install:
  environment:
    filename: 99_my_thing_goes_last
    ops:
      - prepend: PATH
        value: /spfs/bin
```

Here the array of "ops" gets put into a child attribute, in order to have some place to put the new `filename` attribute. We can support parsing both ways.

### Comments

Our tool happens to support generating comments in the activation script. This wouldn't be difficult to support.

```yaml
install:
  environment:
    - comment: START
    - set: KTOA_VERSION
      value: $SPK_PKG_VERSION_BASE
    - set: KATANA_TAGLINE
      value: "With KtoA $${KTOA_VERSION}"
    - comment: END
```

Generated activation script:

```bash
# START
export KTOA_VERSION="4.2.2.0"
export KATANA_TAGLINE="With KtoA ${KTOA_VERSION}"
# END
```
