### ISSUE TITLE
Allow package vars to have documentation

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#943]
At SPI the use of vars, and in particular strong inheritance vars, is growing in complexity. One developer working on a package may be surprised to find unexpected vars showing up in their package's install requirements, because another developer has decided to add a new strong inheritance var to their package.

While that other developer may have taken the time to write some comments in the yaml for their new var, these comments aren't preserved when publishing the package and `spk info <package>` shows no comments at all.

The proposal is to add a new optional field `description` to `var` options that can contain free-form (markdown?) documentation attached to the var so that it is captured into the built package.

```yaml
pkg: lights/1.0.0

build:
  options:
    - var: color/blue
      choices: [red, blue, green]
      description: |
        Control what color the lights will be when lit.
      inheritance: Strong
```

Besides the description being visible when using `spk info lights`, downstream packages that depend on `lights` would also get the description propagated into their builds, as in:

```yaml
pkg: user-of-lights/1.0.0/BUILDGST
...
install:
  requirements:
    - pkg: lights/Binary:1.0.0
    - var: lights.color/green
      description: |
        Control what color the lights will be when lit.
```

This way, someone doing `spk info user-of-lights` doesn't have to go hunting for the spec of `lights` to see the description(s) or track down the source repo to read the comments in the source spec file.
