### ISSUE TITLE
Build digests don't understand components and cause collisions

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#947]
The setup to demonstrate this problem starts with a base package containing two components, and then two variations of a second package that depends on the first.

- base.spk.yaml

```yaml
pkg: base/1.0.0
build:
  script:
    - touch "$PREFIX"/comp1
    - touch "$PREFIX"/comp2

install:
  components:
    - name: comp1
      files:
        - comp1
    - name: comp2
      files:
        - comp2
```
- simple1.spk.yaml

```yaml
pkg: simple/1.0.0
build:
  options:
    - pkg: base:comp1/1.0.0
  script:
    - "true"
```

- simple2.spk.yaml

```yaml
pkg: simple/1.0.0
build:
  options:
    - pkg: base:comp2/1.0.0
  script:
    - "true"
```

Try this at home!

```sh
$ spk build simple1.spk.yaml
 INFO created simple/1.0.0/7QQERXEI
$ spk build simple2.spk.yaml
 INFO created simple/1.0.0/7QQERXEI
```

Both builds were created with the same digest, but these are really two distinct builds.

Or this problem can surface as an error to build a valid package.

- simple.spk.yaml

```yaml
pkg: simple/1.0.0
build:
  script:
    - "true"
  variants:
    - { "base:comp1": "1.0.0" }
    - { "base:comp2": "1.0.0" }
```

```sh
$ spk build simple.spk.yaml
ERROR (link)

  ×
  │  1 | pkg: simple/1.0.0
  │    | ^ Error: Multiple variants would produce the same build:
  │   - {base: 1.0.0} (EH5LEAJX)
  │   - {base: 1.0.0} (EH5LEAJX)
  │    | build:
  │    |   script:
  │    |     - "true"
  │    |   variants:
  │    |     - { "base:comp1": "1.0.0" }
  │    |     - { "base:comp2": "1.0.0" }
  │
```

You may also notice that the digest displayed in this error message does not match the digest shown for what what was created when building as separate spec files. Neither of the digests are truly correct though; to fix this bug the digest needs to incorporate more information than just the build options. What components have been requested is also needed, but this information is lost when converting the pkg requests into options.
