### ISSUE TITLE
Improve user experience for building packages on multiple platforms

### ISSUE THREAD

**Issue by jrray** [spkenv/spk#956]
At present, to build a package for both centos 7 and rocky 9, it is necessary to write two different specs.

Abbreviated examples:

```yaml
# centos.spk.yaml
pkg: demo/1.0.0
build:
  variants:
    - { gcc: 6.3, python: 3.7 }
    - { gcc: 9.3, python: 3.9 }
```

```yaml
# rocky.spk.yaml
pkg: demo/1.0.0
build:
  variants:
    - { gcc: 11.4, python: 3.9 }
```

It is natural for users to want to do this all in a single spec file:

```yaml
# package.spk.yaml
pkg: demo/1.0.0
build:
  variants:
    - { gcc: 6.3, python: 3.7 }
    - { gcc: 9.3, python: 3.9 }
    - { gcc: 11.4, python: 3.9 }
```

This doesn't work because `spk build package.spk.yaml` will fail to build some of the variants on both centos and rocky, due to missing packages, like gcc/9.3 not being present on rocky and gcc/11.4 not being present on centos. It is technically possible to use the _hidden_ `--variants` flag to build individual variants successfully, but this is not user friendly.

The main proposal here is to build some kind of variant filtering mechanism into `spk build`, to cause some variants to be skipped when building on a particular OS.

Here is an example of what users are already intuitively thinking should be possible:

```yaml
# package2.spk.yaml
pkg: demo/1.0.0
build:
  variants:
    - { distro: centos, gcc: 6.3, python: 3.7 }
    - { distro: centos, gcc: 9.3, python: 3.9 }
    - { distro: rocky, gcc: 11.4, python: 3.9 }
```

I agree this is a logical conclusion, since variants are the way for a package author to define the different build flavors of a package that are to be built, and builds for different OSes can be thought of as simply more flavors of the same package.

This approach doesn't work in spk currently because the value of vars can be overridden, an additionally host vars will be overridden automatically. `spk build package2.spk.yaml` on centos would attempt to build all three variants with `distro=centos` and fail to build the third variant.

### Idea One: Immutable Variants

Currently variants don't interact coherently with the command line `--opt` approach of building different flavors of a package.

Take this example package:

```yaml
# package3.spk.yaml
pkg: demo/1.0.0
build:
  options:
    - pkg: gcc/4.8
    - pkg: python/2.7
  variants:
    - { gcc: 6.3, python: 3.7 }
    - { gcc: 9.3, python: 3.9 }
```

Note that the "default" versions of gcc and python are set to versions that don't appear in the variants list.

`spk build package3.spk.yaml` produces two builds (the two variants). Note there's no way to invoke `spk build` to ask it to build the "default variant" with gcc/4.8 and python/2.7. So, what if I want to build it with those versions? `spk build --opt gcc=4.8 --opt python=2.7 package3.spk.yaml` will still build both variants, but it will override the values of gcc and python each time, producing the same build twice[^1].

What if `--opt` was something that worked independent of variants, and was the way to build a _single_ flavor of a package with the specified overrides? In this scenario, all of the following commands would produce the same, single build:

- `spk build --opt gcc=4.8 package3.spk.yaml`
- `spk build --opt python=2.7 package3.spk.yaml`
- `spk build --opt gcc=4.8 --opt python=2.7 package3.spk.yaml`

These would all build the "default variant" while overriding whatever default values, and _ignore the `build.variants` definitions entirely_.

If we establish that using `--opt` bypasses the variants, then we can say that the variants are immutable and `--opt` doesn't override the values of vars defined in them. By extension, `distro: rocky` would not be overridden to `distro: centos` when building on centos. Then, a variant filtering mechanism can be put in place where variants that don't match the current set of overrides are skipped.

This idea has the downside of locking out the ability to build all the variants but with _some_ things overridden. This behavior could perhaps be salvaged with extra command line flags to enable it. To my knowledge this is not a common practice. It reintroduces the problem of allowing host vars to be overridden.

### Idea Two: Host Vars Category

```yaml
# package4.spk.yaml
pkg: demo/1.0.0
build:
  variants:
    - { hostvar.distro: centos, gcc: 6.3, python: 3.7 }
    - { hostvar.distro: centos, gcc: 9.3, python: 3.9 }
    - { hostvar.distro: rocky, gcc: 11.4, python: 3.9 }
```

This idea keeps the concept of filtering on hostvar values but puts host vars into a different category as regular vars. Therefore the value appearing in a variant would not be overridden under normal usage. In the example spec I have put the hostvars into a "hostvar" namespace. This is not necessary but could be helpful to emphasize how they have special meaning. Sites would be free to define their own custom hostvar members and default values.

In this scenario, in addition to `--opt` to override normal vars, there would be a `--host-opt` to override the detected hostvar value(s).

| Command Line | Current OS | Builds Attempted | Comment |
| --- | --- | --- | --- |
| `spk build package4.spk.yaml` | centos | [gcc/6.3, python/3.7], [gcc/9.3, python/3.9] | Skips "rocky" variant |
| `spk build package4.spk.yaml` | rocky | [gcc/11.4, python/3.9] | Skips "centos" variant |
| `spk build --opt python=2.7 package4.spk.yaml` | centos | [gcc/6.3, python/2.7], [gcc/9.3, python/2.7] | Builds "centos" variants with override |
| `spk build --opt python=2.7 package4.spk.yaml` | rocky | [gcc/11.4, python/2.7] | Builds "rocky" variants with override |
| `spk build --host-opt distro=rocky package4.spk.yaml` | centos | [gcc/11.4, python/3.9] | Behaves as if were running on rocky (detected value overridden) |
| **`--opt` with host var behavior alternate 1** | | | The "safe" behavior |
| `spk build --opt distro=centos package4.spk.yaml` | * | n/a | Error: host vars cannot be overridden with `--opt` |
| **`--opt` with host var behavior alternate 2** | | | Allows more flexibility, but allows for "unsafe" behaviors |
| `spk build --opt distro=centos package4.spk.yaml` | centos | [gcc/6.3, python/3.7], [gcc/9.3, python/3.9], [gcc/11.4, python/3.9] | All variants redefined as `hostvar.distro: centos` so they all match (but some variants will probably fail to build) |
| `spk build --opt distro=centos package4.spk.yaml` | rocky | None | All variants redefined as `hostvar.distro: centos` so none match (not useful) |
| `spk build --opt distro=centos --host-opt distro=centos package4.spk.yaml` | rocky | [gcc/6.3, python/3.7], [gcc/9.3, python/3.9], [gcc/11.4, python/3.9] | All variants redefined as `hostvar.distro: centos` _and_ distro overridden to "centos" so they all match (but some variants will probably fail to build)[^2] |

[^1]: Yes, it could be smarter and skip variants that are duplicates.
[^2]: This will create builds built on rocky but marked as built/compatible with centos a.k.a. "cross compiling" which is questionable to allow.
