### ISSUE TITLE
Allow compat to be specified in pkg requests

### ISSUE THREAD

**Issue by rydrman** [spkenv/spk#97]
Coming out of the meeting today, the idea is to expose the `required_compat` field of package requests so that they can be specified in spec files and on the command line if needed.

```yaml
build:
  options:
    - {pkg: boost, compat: API}
```
